monitored_urls:
  - https://docs.aws.amazon.com/eks/latest/userguide/al2023.html
  #- https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

notify_emails:
  - viveksbhadauria007@gmail.com
